import { AppSchema } from '@store/schema/latest';

export const apps = [
  {
    name: 'docs',
    url: 'https://crossmark.io',
    type: 'app',
    categories: ['docs'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: {
      expires: Date.now() + 60 * 60 * 24 * 30,
      duration: 60 * 60 * 24 * 30,
      isExpired: false,
      isRevoked: false,
      dateGranted: Date.now(),
      dateRevoked: undefined,
    },
    grants: {
      viewBalance: false,
      viewCurrentCard: false,
      viewCurrentNetwork: false,
      viewContacts: false,
      viewAllCards: false,
      promptSignRequest: false,
      allowableTxTypes: ['all'],
    },
  },
  {
    name: 'MoonPay',
    url: 'https://buy.moonpay.com/?apiKey=[your_api_key]',
    type: 'app',
    categories: ['ramp'],
    img: 'https://www.moonpay.com/favicon-purple-32x32.png',
    bg: 'light',
    approved: true,
    access: {
      expires: Date.now() + 60 * 60 * 24 * 30,
      duration: 60 * 60 * 24 * 30,
      isExpired: false,
      isRevoked: false,
      dateGranted: Date.now(),
      dateRevoked: undefined,
    },
    grants: {
      viewBalance: false,
      viewCurrentCard: false,
      viewCurrentNetwork: false,
      viewContacts: false,
      viewAllCards: false,
      promptSignRequest: false,
      allowableTxTypes: [],
    },
  },
  {
    name: 'Stably',
    url: 'https://ramp.stably.io/?network=xrpl&asset=USDS&lock=true&integrationId=crossmark-58fecdaf',
    type: 'app',
    categories: ['ramp'],
    img: 'https://ramp.stably.io/images/stably_gradient_favicon.ico',
    bg: 'light',
    approved: true,
    access: {
      expires: Date.now() + 60 * 60 * 24 * 30,
      duration: 60 * 60 * 24 * 30,
      isExpired: false,
      isRevoked: false,
      dateGranted: Date.now(),
      dateRevoked: undefined,
    },
    grants: {
      viewBalance: false,
      viewCurrentCard: false,
      viewCurrentNetwork: false,
      viewContacts: false,
      viewAllCards: false,
      promptSignRequest: false,
      allowableTxTypes: [],
    },
  },
  {
    name: 'XRPL Merch',
    url: 'https://xrplmerch.com/',
    type: 'app',
    categories: ['merch'],
    img: 'https://xrplmerch.com/wp-content/uploads/2021/11/cropped-XRPLMerchLogoSmall-1-192x192.png',
    bg: 'dark',
    approved: true,
    access: {
      expires: Date.now() + 60 * 60 * 24 * 30,
      duration: 60 * 60 * 24 * 30,
      isExpired: false,
      isRevoked: false,
      dateGranted: Date.now(),
      dateRevoked: undefined,
    },
    grants: {
      viewBalance: false,
      viewCurrentCard: false,
      viewCurrentNetwork: false,
      viewContacts: false,
      viewAllCards: false,
      promptSignRequest: false,
      allowableTxTypes: [],
    },
  },
  {
    name: 'bithomp',
    url: 'https://bithomp.com',
    type: 'link',
    categories: ['explorer'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'xumm',
    url: 'https://xumm.app',
    type: 'link',
    categories: ['tool'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'xrpl.org',
    url: 'https://xrpl.org',
    type: 'link',
    categories: ['docs'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'xrplmeta',
    url: 'https://xrplmeta.org',
    type: 'link',
    categories: ['tool'],
    img: '/x/icon@128x128.png',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'sologenic',
    url: 'https://sologenic.org/trade',
    type: 'link',
    categories: ['exchange'],
    img: 'https://sologenic.org/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'onthedex',
    url: 'https://onthedex.live',
    type: 'link',
    categories: ['exchange'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'xrpltoolkit',
    url: 'https://www.xrptoolkit.com',
    type: 'link',
    categories: ['tool'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'XDEX',
    url: 'https://xdex.com',
    type: 'link',
    categories: ['exchange'],
    img: '/x/logo@128x128.png',
    bg: 'dark',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'onXRP',
    url: 'https://onxrp.com',
    type: 'link',
    categories: ['nft', 'exchange'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'xrp.cafe',
    url: 'https://xrp.cafe',
    type: 'link',
    categories: ['nft'],
    img: '/assets/fav/favicon-32x32.png',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'xpmarket',
    url: 'https://xpmarket.com',
    type: 'link',
    categories: ['nft', 'exchange'],
    img: '/images/favicon/favicon-32x32.png',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'XRPSCAN',
    url: 'https://xrpscan.com',
    type: 'link',
    categories: ['explorer'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'XRPL.to',
    url: 'https://xrpl.to',
    type: 'link',
    categories: ['explorer'],
    img: '/favicon-96x96.png',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'xrpl.org',
    url: 'https://livenet.xrpl.org',
    type: 'link',
    categories: ['explorer'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'XRPLF Explorer',
    url: 'https://explorer.xrplf.org',
    type: 'link',
    categories: ['explorer'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'Three XRP',
    url: 'https://threexrp.dev',
    type: 'link',
    categories: ['explorer'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'XRPL Services',
    url: 'https://xrpl.services',
    type: 'link',
    categories: ['statistics', 'tool'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'Discord',
    url: 'https://discord.gg/xrpl',
    type: 'link',
    categories: ['resources'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'Dev.to',
    url: 'https://dev.to/ripplexdev',
    type: 'link',
    categories: ['resources'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'XRPL Ideas Discussion',
    url: 'https://github.com/intelliot/xrpl-ideas/discussions',
    type: 'link',
    categories: ['resources'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
  {
    name: 'XRP Ledger Foundation Youtube',
    url: 'https://www.youtube.com/channel/UC6zTJdNCBI-TKMt5ubNc_Gg',
    type: 'link',
    categories: ['resources'],
    img: '/favicon.ico',
    bg: 'light',
    approved: true,
    access: undefined,
    grants: undefined,
  },
] as AppSchema[];
